language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python3-numpy
    - python3-scipy
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8 .
  - coverage run --source=libmozdata -m unittest discover tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: pip
