language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codecov
script:
  - coverage run --source=clouseau -m unittest discover tests/
after_success:
  - codecov
script:
  - python -m unittest discover tests/
  - flake8 .
